<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All your tickets<br> in one place' => '轻松刷“环”,<br>便利买票',
  'If you want your tickets close to hand,<br> put them on your wrist.' => '想把各种公共交通票都“戴”在你的手腕上吗?<br>智能手环帮你实现!',
  'Make a lasting<br> connection' => '建立联系',
  'Met someone?<br> Share your details instantly with Mobispot.<br> Like something?<br> Share it, and brands can share right back.' => '认识了新朋友?<br>轻松刷“环”,  与好友们分享自己的全部. <br>点赞了网页?<br>获得各种名牌的折扣和优惠.',
  'One tap is<br> all it takes' => '轻轻一触,<br>刷“环”过关',
  'Pay with a tap,<br> not with cash' => '轻轻一触,<br>刷“环”付款',
  'Save time, carry less. You can keep<br> your loyalty cards, tickets and<br> membership details on your Spot.' => '节省时间的好帮手 - 打折卡, 公车票,<br>出入证, 全部刷“环”, <br>无所不能!',
  'Spend less time paying for lunch,<br> spend more time eating it. Mobispot works<br> with your campus payment scheme.' => '便利的小金额付款方式, <br>智能手环让你足不出户, <br>轻松付款.',
  '© Мобиспот. Корпоративные сервисы. Все права защищены' => '',
  'Назад' => '',
  'Оферта' => '',
  'Показать ещё' => '',
  'Помощь' => '',
  'Условия использования' => '',
);
