<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => '电子邮箱',
  'Get Help' => '帮助',
  'Have a question? Need a hand? 
                            Anything bugging you?
                            Please stick your details in this form and we’ll get back to you. Pronto. If not sooner.' 
        => 
        '需要帮助或有疑问？请填写下列信息以便我们尽快联系您。',
  'If you have a suggested answer, please let us know' => '如果你知道可行的问题解决方法，请告知我们',
  'Hook up at Facebook' => '在 Facebook 关注我们',
  'Keep up at Twitter' => '在推特关注我们',
  'Name' => '姓名',
  'Phone' => '手机',
  'Question' => '问题',
  'Question has been submitted' => '',
  'Send' => '发送',
);
