<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contactless readers' => '感应式解读器',
  'Device compatibility' => '兼容设备',
  'Help' => '帮助',
  'Phones & tablets' => '手机平板电脑',
  'Please note: ' => '请注意：',
  'Readers' => '解读器',
  'Some devices specifications change regularly and depend on the sales region. For the most accurate information check with your retailer or mobile operator that NFC is enabled on your device.' => '根据购买地区不同，部分产品特性可能会发生变化。请向你的运营商确认设备是否支持近场通讯（NFC）。',
  'Special app needed. These devices must have special app to read the spots:' => '使用手环需安装：',
  'Spots can be read by many popular phones and tablets with NFC functionality.<br> Here is the list of currently supported devices:' => '手环适用于大多数支持近场通讯（NFC）的移动设备，列表如下：',
  'We have tested and verified compatibility with the following readers:' => '我们已检测手环与以下解读器的兼容性：',
);
