<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add another spot' => '',
  'Are you sure?' => '',
  'Bring back your spot\'s content to your friends' => '',
  'Clean spot' => '',
  'Continue?' => '',
  'Create a 4-digit password to protect your spot\'s content. Tell this password only to trusted people.' => '',
  'Delete your spot' => '',
  'Enter spot\'s password' => '',
  'Erase all the content of your spot with one click. You will not be able to cancel this action.' => '',
  'Hide the content of your spot from other people. When they tap it with phone they will see page 404' => '',
  'I agree to Mobispot Pages Terms' => '同意使用条件',
  'Load a new spot' => '',
  'Make spot invisible' => '',
  'Make spot visible' => '',
  'Make your spot disappear forever from your personal account. You will not be able to cancel this action or to re-store your spot.' => '',
  'New Name' => '',
  'New Password' => '',
  'No' => '',
  'Oops!' => '',
  'Rename spot' => '',
  'Reset Password' => '',
  'Save' => '',
  'Saved!' => '',
  'Set password' => '',
  'Spot activation code' => '激活码',
  'Spot name' => '',
  'There was an error when attempting to upload this file<br/>Please try again' => '',
  'Yes' => '',
  'Вы еще не активировали кошелёк для этого спота!' => '',
  'Подключить' => '',
  'Учавствую' => '',
);
