<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' views' => '',
  'Account is blocked ...' => '',
  'Activate spot' => '',
  'Add file' => '',
  'Add new spot' => '',
  'Another attempt will be performed in' => '',
  'Attention! To link the bank card with your spot we will have to charge you $0.029.' => '',
  'Block wallet' => '',
  'Clean all the content from your spot.<br /> Will be impossible to restore.' => '',
  'Clean spot' => '',
  'Close form' => '',
  'Coupon' => '',
  'Current' => '',
  'Delete spot' => '',
  'Delete the spot from your account.<br /> Attention: Will be impossible to restore.' => '',
  'Demo' => '',
  'Description' => '',
  'Download' => '',
  'Edit the list' => '',
  'Enter spot\'s password' => '',
  'Finish editing' => '',
  'Full' => '',
  'GB' => '',
  'Get the statement' => '',
  'I agree to Mobispot Pages Terms' => '',
  'Kb' => '',
  'Link a bank card' => '',
  'Link your bank cards with your wallet to make payments using your spot' => '',
  'Linking your card is in progress. Please wait a minute.' => '',
  'MB' => '',
  'Make current' => '',
  'Make spot invisible' => '',
  'Make spot visible' => '',
  'Make your spot invisible/visible for the handsets' => '',
  'Maximum file size cannot be greater than 25mb' => '',
  'Move your link' => '',
  'My bank cards' => '',
  'Name cannot be longer than 15 symbols. <br /> May consist of Cyrillic, Latin and digits.' => '',
  'Oops!' => '',
  'Please read and confirm that you accept the' => '',
  'Please type your new spot’s activation code and click the button below.' => '',
  'Post' => '',
  'Recent transactions' => '',
  'Remove' => '',
  'Rename' => '',
  'Saved' => '',
  'Service is currently not available' => '',
  'Settings' => '',
  'Size' => '',
  'Social links' => '',
  'Spot activation code ' => '',
  'Spot\'s URL' => '',
  'Tap to Download' => '',
  'There was an error when attempting to upload this file<br/>Please try again' => '',
  'Type' => '',
  'Type the text and links or drag your files here' => '',
  'Unblock' => '',
  'User agreement confirmation' => '',
  'Wallet' => '',
  'Yandex.Money User Agreement' => '',
  'Yes, I accept the agreement' => '',
  'You are participating in the action' => '',
  'You don’t have any bank cards linked with your spot.' => '',
  'bytes' => '',
  'seconds' => '',
  'views' => '',
);
