<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Вам необходимо выбрать тип вашего первого спота.' => 'You need to select the type of your first spot.',
  'Мои споты' => 'My Spots',
  'Назад' => 'Back',
  'Начните использовать Ваш спот<br /> прямо сейчас' => 'Start using your spot<br /> right now',
  'Перейти в личный кабинет' => 'Go to your personal cabinet',
  'Показать ещё' => 'how more',
  'Сохранить' => 'Save',
  'Храните и передавайте информацию<br /> по-новому. С помощью NFC' => 'New ways to store and transmit information via NFC',
);
