<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Email' => '',
  'Ближайшие точки прода' => '',
  'Ваш отзыв успешно отправлен' => '',
  'Введите адрес электронной почты и Вам отправят файлы' => '',
  'Для продолжения работы с сайтом вам необходимо ввести код изображенный на картинке.' => '',
  'Забыли пароль?' => '',
  'Имя' => '',
  'Интересные предложение' => '',
  'Комментарий' => '',
  'Материалы успешно отправлены на Ваш e-mail' => '',
  'Необходимо заполнить все поля.' => '',
  'Оставить комментарий' => '',
  'Отправить' => '',
  'Отправить ещё' => '',
  'Отправка на E-mail' => '',
  'Полная версия' => '',
  'Смотреть видео о Мобиспот' => '',
  'Сохранить визитку' => '',
  'Телефон' => '',
  'Я согласен с правилами пользования сервиса' => '',
);
