<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'E-mail' => 'E-mail',
  'E-mail не валиден' => '',
  'Email' => 'E-mail',
  'Email is incorrect.' => '',
  'Hа сайте не зарегистрирован пользователь с таким Email.' => '',
  'Id' => '',
  'Incorrect password (minimal length 5 symbols).' => '',
  'Minimal password length 5 symbols.' => '',
  'Password is incorrect.' => '',
  'Please activate you account go to {activation_url}' => '',
  'Register' => '',
  'Registration' => '',
  'Remember me next time' => '',
  'Retype Password' => '',
  'Retype Password is incorrect.' => '',
  'Thank you for your registration. Please check your email.' => '',
  'You account is blocked.' => '',
  'You account is not activated.' => '',
  'You are not allowed to perform this action.' => '',
  'You registered from {site_name}' => '',
  'password' => '',
  'Авторизация' => '',
  'Админ' => '',
  'Активация пользователя' => '',
  'Активен' => '',
  'Активирован' => '',
  'Введите код показанный на картинке' => 'Please enter the characters you see below',
  'Введите новый пароль.' => '',
  'Войти' => 'Sign in',
  'Восстановить' => '',
  'Вы должны согласиться с условиями предоставления сервиса' => 'You must agree to the terms of service',
  'Вы не правильно ввели комбинацию логина<br/> и пароля. Пожалуйста повторите попытку' => '',
  'Вы не правильно заполнили поля.' => '',
  'Дата последнего посещения' => '',
  'Дата регистрации' => '',
  'Если Вы забыли свой пароль и хотите его восстановить,<br /> введите адрес электронной почты,<br /> который Вы использовали при регистрации.' => '',
  'Женский' => 'Female',
  'Заблокирован' => '',
  'Забыли пароль?' => 'Forgot your password?',
  'Закрыть' => '',
  'Запомнить меня' => 'Remember me',
  'Зарегистрироваться' => 'Sign up',
  'Имя' => 'Name',
  'Ключ активации' => '',
  'Код активации должен иметь длину 10 символов' => 'Spot activation code is too short',
  'Код активации спота' => 'Spot activation code',
  'Код активации спота неверен' => 'Wrong spot activation code',
  'Минимальная длина пароля 5 символов' => 'Password is too short',
  'Мужской' => 'Male',
  'На сайте уже зарегистрирован пользователь с таким Email' => '',
  'Не активирован' => '',
  'Неверная активационная ссылка.' => '',
  'Необходимо указать код активации спота' => 'You must specify the spot activation code',
  'Неправильный код проверки' => 'Code from the image is incorrect',
  'Отправить' => 'Log In',
  'Пароли не совпадают' => '',
  'Пароль' => 'Password',
  'Пароль или логин не верен.' => '',
  'По указанному вами адресу отправлено письмо<br/> с информацией о востановлении пароля.' => '',
  'Повтор пароля' => 'Confirm password',
  'Подтверждение Email' => '',
  'Подтверждение пароля' => 'Confirm password',
  'Пожалуйста введите код показанный на картинке' => 'Please enter the characters you see below',
  'Пользователь' => '',
  'Проверочный код' => '',
  'Смена пароля' => '',
  'Спасибо за регистрацию на нашем сайте,<br /> на указанный вами Email была отправлено письмо<br /> с инструкцией по активации вашей учётной записи.' => '',
  'Статус' => '',
  'Тип' => '',
  'У вас не хватает прав для доступа.' => 'You do not have permission to access.',
  'Я согласен с условиями предоставления сервиса' => 'I agree to the terms of service',
);
