<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'Active' => '',
    'Admin' => '',
    'Banned' => '',
    'E-mail' => '',
    'Email is incorrect.' => '',
    'Id' => '',
    'Incorrect password (minimal length 5 symbols).' => '',
    'Last visit' => '',
    'Not active' => '',
    'Password is incorrect.' => '',
    'Registration date' => '',
    'Remember me next time' => '',
    'Retype Email' => '',
    'Retype Email is incorrect.' => '',
    'Retype Password' => '',
    'Retype Password is incorrect.' => '',
    'Status' => '',
    'The activation code is incorrect spot.' => '',
    'This user\'s email address already exists.' => '',
    'To register, you must agree to the terms of this agreement' => '',
    'Type' => '',
    'User' => '',
    'Verification Code' => '',
    'You account is blocked.' => '',
    'You account is not activated.' => '',
    'You are not allowed to perform this action.' => '',
    'activation key' => '',
    'password' => '',
    'Incorrect password (minimal length5 symbols).' => '@@@@',
);
