<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
    'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' => '',
    'Can\'t save document to disk, or try to save empty document!' => '',
    'Can\\t save document to disk, or try to save empty document!' => '',
    'Cannot create PK criteria for multiple composite key\'s (not implemented yet)' => '',
    'EMongoDB failed to open connection: {error}' => '',
    'EMongoDB.connectionString cannot be empty.' => '',
    'EMongoDbFixtureManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => '',
    'The EMongoDocument cannot be deleted because it is new.' => '',
    'The EMongoDocument cannot be inserted to database because it is not new.' => '',
    'The EMongoDocument cannot be inserted to database primary key is not defined.' => '',
    'The EMongoDocument cannot be updated because it is new.' => '',
    'We need a filename' => '',
    'Your request is invalid.' => '',
    '{attribute} is not unique in DB.' => '',
);
