<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'All your tickets<br> in one place' => '便利刷"環"，輕鬆購票。',
  'If you want your tickets close to hand,<br> put them on your wrist.' => '想把各種車票都"戴"在你的手腕上嗎？智能手環幫你實現！',
  'Make a lasting<br> connection' => '建立聯系',
  'Met someone?<br> Share your details instantly with Mobispot.<br> Like something?<br> Share it, and brands can share right back.' => '認識了新朋友？<br>輕鬆刷"環"，與好友們分享自己的全部。<br>按個讚？<br>獲得各大知名品牌的折扣和優惠。',
  'One tap is<br> all it takes' => '輕鬆感應，暢行無阻。',
  'Pay with a tap,<br> not with cash' => '輕鬆感應，刷"環"付款',
  'Save time, carry less. You can keep<br> your loyalty cards, tickets and<br> membership details on your Spot.' => '节省时间的好帮手 - 貴賓卡、公車票、門禁卡、全部刷"環"，無所不能！',
  'Spend less time paying for lunch,<br> spend more time eating it. Mobispot works<br> with your campus payment scheme.' => '便利的小額付款，智能手環讓你在家購物，輕鬆付款。',
  '© Мобиспот. Корпоративные сервисы. Все права защищены' => '',
  'Назад' => '',
  'Оферта' => '',
  'Показать ещё' => '',
  'Помощь' => '',
  'Условия использования' => '',
);
