<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => '電子郵箱',
  'Get Help' => '幫助',
  'Have a question? Need a hand? 
                            Anything bugging you?
                            Please stick your details in this form and we’ll get back to you. Pronto. If not sooner.' 
        => 
        '需要幫助或有疑問？請填寫下列信息以便我們儘快與您聯繫。',
  'If you have a suggested answer, please let us know' => '如果你已知可行的問題解決方法，請告知我們',
  'Hook up at Facebook' => '在 Facebook 關注我們',
  'Keep up at Twitter' => '在推特關注我們',
  'Name' => '姓名',
  'Phone' => '手機',
  'Question' => '問題',
  'Question has been submitted' => '',
  'Send' => '發送',
);
