<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contactless readers' => '感應式掃描器',
  'Device compatibility' => '相容裝置',
  'Help' => '幫助',
  'Phones & tablets' => '手機平板電腦',
  'Please note: ' => '請注意：',
  'Readers' => '掃描器',
  'Some devices specifications change regularly and depend on the sales region. For the most accurate information check with your retailer or mobile operator that NFC is enabled on your device.' => '根據購買地區不同，部分產品特性可能會發生變化。請向您的供應商確認設備是否支援近距離無線通訊（NFC）。',
  'Special app needed. These devices must have special app to read the spots:' => '使用手環需安裝：',
  'Spots can be read by many popular phones and tablets with NFC functionality.<br> Here is the list of currently supported devices:' => '手環適用于大多數支持近距離無線通訊（NFC）的移動設備，列表如下：',
  'We have tested and verified compatibility with the following readers:' => '我們已檢測手環與以下掃描器的相容性： 
',
);
