<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'A letter with instructions has been sent to your email address. Thank you.' => '',
  'Activate spot' => '',
  'Bad Request' => '',
  'Birthday' => '',
  'Change password' => '',
  'Check your email and password' => '',
  'City' => '',
  'Connect your Mobispot profile with your favourite social network accounts. This will make your sign in easy. If you connect several accounts you will be able to sign in with any of them.' => '',
  'E-mail' => '',
  'Easy sign in' => '',
  'Email' => '',
  'Email address' => '',
  'Email is incorrect.' => '',
  'Error' => '',
  'Female' => '',
  'Forbidden.' => '',
  'Forgot password?' => '',
  'I agree to Terms and Conditions' => '',
  'Incorrect activation link' => '',
  'Incorrect password (minimal length 5 symbols).' => '',
  'Male' => '',
  'Minimum password length 2 characters' => '',
  'Name' => '',
  'New password' => '',
  'Not specified' => '',
  'Note: This action will not connect your spots\' content with your social networks. Please make it separately when editing your spots.' => '',
  'Password' => '',
  'Password change' => '',
  'Password is incorrect.' => '',
  'Password is too short (minimum is 5 characters).' => '',
  'Personal data' => '',
  'Profile info' => '',
  'Register spot' => '',
  'Remember me next time' => '',
  'Retype Password' => '',
  'Retype Password is incorrect.' => '',
  'Save' => '',
  'Send' => '',
  'Send to email' => '',
  'Sign in' => '',
  'Spot activation code' => '',
  'Start using your spot right now' => '',
  'The activation code is wrong spot' => '',
  'The information has been saved successfully' => '',
  'The requested page does not exist.' => '',
  'The site already a registered member with Email' => '',
  'This email has been already used' => '',
  'User activation' => '',
  'Wrong activation code' => '',
  'You account is blocked.' => '',
  'You account is not activated.' => '',
  'You and your first spot have been registred successfully. Please check your inbox to confirm registration.' => '',
  'You can change your password following the instructions in a special email from us. Please click the button below to proceed.' => '',
  'You\'ve made a mistake in spot activation code.' => '',
  'password' => '',
);
