<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => '',
  'Get Help' => '',
  'Have a question? Need a hand?
                            Anything bugging you?
                            Please stick your details in this form and we’ll get back to you. Pronto. If not sooner.' => '',
  'Hook up at Facebook' => '',
  'If you have a suggested answer, please let us know' => '',
  'Keep up at Twitter' => '',
  'Name' => '',
  'Phone' => '',
  'Question' => '',
  'Question has been submitted' => '',
  'Send' => '',
);
