<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Email' => 'Адрес эл. почты',
  'Get Help' => 'Помощь',
  'Have a question? Need a hand? 
                            Anything bugging you?
                            Please stick your details in this form and we’ll get back to you. Pronto. If not sooner.' 
        => 
        'Есть вопрос? Нужна помощь? 
                            Что-то беспокоит? 
                            Пожалуйста, заполните данную форму, и мы с Вами свяжемся в ближайшее время. ',
  'Hook up at Facebook' => 'Следите за нами в Facebook',
  'If you have a suggested answer, please let us know' => 'Если Вы знаете возможное решение проблемы, пожалуйста, сообщите нам',
  'Keep up at Twitter' => 'Читайте нас в Twitter',
  'Name' => 'Имя',
  'Phone' => 'Телефон',
  'Question' => 'Вопрос',
  'Question has been submitted' => 'Ваш вопрос был отправлен. Спасибо!',
  'Send' => 'Отправить',
);
