<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Contactless readers' => 'Бесконтактные считыватели',
  'Device compatibility' => 'Совместимые устройства',
  'Help' => 'Помощь',
  'Phones & tablets' => 'Телефоны и планшеты',
  'Please note: ' => 'Внимание:',
  'Readers' => 'Ридеры (считыватели)',
  'Some devices specifications change regularly and depend on the sales region. For the most accurate information check with your retailer or mobile operator that NFC is enabled on your device.' => 'Техническая спецификация некоторых устройств может меняться и зависит от региона продаж. Пожалуйста, уточняйте у своего продавца или оператора мобильной связи, поддерживает ли устройство функцию NFC.',
  'Special app needed. These devices must have special app to read the spots:' => 'Необходимо 
специальное приложение. Для чтения спотов на этих девайсах должно быть установлено специальное приложение:',
  'Spots can be read by many popular phones and tablets with NFC functionality.<br> Here is the list of currently supported devices:' => 'Споты могут быть прочитаны большинством популярных мобильных устройств с функцией NFC.<br> Вот список поддерживаемых в настоящее время устройств:',
  'We have tested and verified compatibility with the following readers:' => 'Мы проверили совместимость Спотов со следующими считывателями:',
);
