<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' views' => ' просмотры',
  'Account is blocked ...' => 'Кошелек заблокирован ...',
  'Activate spot' => 'Активировать',
  'Add file' => 'Добавить файл',
  'Add new spot' => 'Добавить спот',
  'Another attempt will be performed in' => 'Новая попытка будет предпринята через',
  'Attention! To link the bank card with your spot we will have to charge you $0.029.' => 'Внимание! Для связывания банковской карты с вашим спотом потребуется списание в размере 1 руб.',
  'Block wallet' => 'Заблокировать кошелек',
  'Clean all the content from your spot.<br /> Will be impossible to restore.' => 'Отчистить с вашего спота все содержимое.<br />
Восстановить будет невозможно.',
  'Clean spot' => 'Отчистить спот',
  'Close form' => 'Закрыть',
  'Coupon' => 'Купон',
  'Current' => 'Платежная',
  'Delete spot' => 'Удалить спот',
  'Delete the spot from your account.<br /> Attention: Will be impossible to restore.' => 'Удалить спот с вашего аккаунта.<br />
Внимание: Восстановить  будет невозможно.',
  'Demo' => 'Демо',
  'Description' => 'Описание',
  'Download' => 'Скачать',
  'Edit the list' => 'Редактировать список',
  'Enter spot\'s password' => 'Введите пароль',
  'Finish editing' => '',
  'Full' => 'Полный',
  'GB' => 'Гб',
  'Get the statement' => 'Выписка по всем операциям',
  'I agree to Mobispot Pages Terms' => 'Я согласен с правилами сервиса Mobispot',
  'Kb' => 'Кб',
  'Link a bank card' => 'Привязать карту',
  'Link your bank cards with your wallet to make payments using your spot' => 'Для совершения платежей свяжите ваш спот с вашими банковскими картами
',
  'Linking your card is in progress. Please wait a minute.' => 'Происходит процесс связывания. Пожалуйста, подождите минуту.',
  'MB' => 'Мб',
  'Make current' => 'Сделать платежной',
  'Make spot invisible' => 'Сделать спот невидимым',
  'Make spot visible' => 'Сделать спот видимым',
  'Make your spot invisible/visible for the handsets' => 'Сделайте ваш спот невидимым/видимым для мобильных устройств',
  'Maximum file size cannot be greater than 25mb' => 'Максимальный размер файла не должен превышать 25мб',
  'Move your link' => '',
  'My bank cards' => 'Мои банковские карты',
  'Name cannot be longer than 15 symbols. <br /> May consist of Cyrillic, Latin and digits.' => 'Длина не должна превышать 15 символов.<br />
Может содержать только: кириллицу, латиницу и цифровое значение.',
  'Oops!' => '',
  'Please read and confirm that you accept the' => 'Пожалуйста, прочитайте и подтвердите ',
  'Please type your new spot’s activation code and click the button below.' => 'Пожалуйста, введите код активации вашего спота',
  'Post' => 'Сохранить',
  'Recent transactions' => 'Последние операции',
  'Remove' => 'Удалить',
  'Rename' => 'Переименовать',
  'Saved' => 'Сохранено',
  'Service is currently not available' => 'Оплата временно не доступна',
  'Settings' => 'Настройки',
  'Size' => 'Размер',
  'Social links' => 'Соц. сети',
  'Spot activation code ' => 'Код активации',
  'Spot\'s URL' => 'Адрес страницы спота',
  'Tap to Download' => '',
  'There was an error when attempting to upload this file<br/>Please try again' => 'При закачке файла произошла ошибка.</br /> Попробуйте ещё раз.',
  'Type' => 'Тип',
  'Type the text and links or drag your files here' => 'Введите текст и ссылки или перетяните сюда ваши файлы',
  'Unblock' => 'Разблокировать',
  'User agreement confirmation' => 'Принятия условий использования',
  'Wallet' => 'Кошелек',
  'Yandex.Money User Agreement' => 'Соглашение об использовании сервиса «Яндекс.Деньги»',
  'Yes, I accept the agreement' => 'Да, я принимаю соглашение',
  'You are participating in the action' => 'Вы участвуете в акции',
  'You don’t have any bank cards linked with your spot.' => 'У вас нет банковский карт, связанных с вашим спотом.',
  'bytes' => 'байт',
  'seconds' => 'секунд',
  'views' => 'просмотры',
);
