<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'E-mail' => '',
  'E-mail не валиден' => '',
  'Email' => '',
  'Email is incorrect.' => '',
  'Id' => '',
  'Incorrect password (minimal length 5 symbols).' => '',
  'Password is incorrect.' => '',
  'Please activate you account go to {activation_url}' => '',
  'Remember me next time' => '',
  'Retype Password' => '',
  'Retype Password is incorrect.' => '',
  'Thank you for your registration. Please check your email.' => '',
  'You account is blocked.' => '',
  'You account is not activated.' => '',
  'You are not allowed to perform this action.' => '',
  'You registered from {site_name}' => '',
  'password' => '',
  'Админ' => '',
  'Активация пользователя' => '',
  'Активен' => '',
  'Активирован' => '',
  'Вы должны согласиться с условиями предоставления сервиса' => '',
  'Дата последнего посещения' => '',
  'Дата регистрации' => '',
  'Женский' => '',
  'Заблокирован' => '',
  'Имя' => '',
  'Ключ активации' => '',
  'Код активации должен иметь длину 10 символов' => '',
  'Код активации спота неверен' => '',
  'Минимальная длина пароля 5 символов' => '',
  'Мужской' => '',
  'На сайте уже зарегистрирован пользователь с таким Email' => '',
  'Не активирован' => '',
  'Неверная активационная ссылка.' => '',
  'Необходимо указать код активации спота' => '',
  'Неправильный код проверки' => '',
  'Пароли не совпадают' => '',
  'Пароль' => '',
  'Подтверждение Email' => '',
  'Подтверждение пароля' => '',
  'Пользователь' => '',
  'Проверочный код' => '',
  'Статус' => '',
  'Тип' => '',
  'У вас не хватает прав для доступа.' => '',
);
