<?php

return array(
    'application.models.*',
    'application.models.form.*',
    'application.models.spot.*',
    'application.models.spot.form.*',
    'application.models.user.*',
    'application.models.user.form.*',
    'application.models.content.*',
    'application.models.content.form.*',
    'application.models.payment.*',
    'application.models.store.*',
    'application.models.term.*',
    'application.components.*',
    'application.helpers.*',
    'ext.eoauth.*',
    'ext.eoauth.lib.*',
    'ext.lightopenid.*',
    'ext.eauth.*',
    'ext.eauth.services.*',
    'ext.eauth.custom_services.*',
    'application.extensions.phpass.*',
    'application.extensions.image.*',
);